# Site settings
title: Wedding Viktoriia & Danylo 
description: "Wedding Viktoriia & Danylo"
url: https://nikache.github.io/Wedding-day-V-D/
baseurl: ''
profilepic: '/images/7.jpg'
bkimage: '/images/dance.jpg'
google_analytics: UA-XXXXXX-X
font_awesome: '4a93e3e01d.js'

author:
  name: 'Viktoriia Bliashynets & Danylo Khilko'
  # email: dkhilko@ukr.net
  # facebook_username: danylo.khilko
 # github_username:
  # linkedin_username: danylo-khilko-785137153


# Build settings
destination: _site
markdown: kramdown
highlighter: rouge

sass:
    sass_dir: _sass
    style: compressed
plugins: 
- jekyll-sitemap
- jekyll-seo-tag

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

#plugins: ['jekyll-paginate']
exclude: ['README.md']
